import turtle
wn = turtle.Screen()
wn.title("Nilesh--Shapes Demo")
wn.bgcolor("BlanchedAlmond")

alex = turtle.Turtle()
alex.shape("turtle")
alex.forward(60)
alex.left(80)
alex.forward(60)
alex.left(100)
alex.hideturtle()
alex.forward(60)
alex.left(80)
alex.forward(60)
wn.mainloop()